services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: my-api
    container_name: my-api
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - /app/node_modules
    environment:
      - DATABASE_URL=mongodb://db:27017/mydatabase
    command: npm run start:dev
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: my-web
    container_name: my-web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: mongo:8.2.2
    container_name: my-db
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok", "-u", "root", "-p", "example", "--authenticationDatabase", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  db-web:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: my-db-web
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_OPTIONS_CONNECT_TIMEOUT_MS: 5000
      ME_CONFIG_OPTIONS_SERVER_CONNECT_TIMEOUT_MS: 5000
    depends_on:
      db:
        condition: service_healthy

volumes:
  mongo-data:
